<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="FluentValidation" Version="10.4.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="10.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project.Domain\Project.Domain.csproj" />
  </ItemGroup>

</Project>
